# Generated by Django 5.2 on 2025-05-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='fees',
            new_name='consultion_fees',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
