# Generated by Django 5.2 on 2025-05-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_fees_doctor_consultion_fees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='consultion_fees',
            new_name='first_visit',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='follow_up_fees',
            new_name='follow_up',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='years_of_experience',
        ),
    ]
